# Generated by Django 5.0.8 on 2024-08-17 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='article_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
