name: Angular CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd FRONTEND
          npm install

      - name: Run tests
        run: |
          npm run test -- --watch=false

      - name: Build
        run: |
          npm run build --prod

      - name: Deploy
        # Here you would add steps to deploy your Angular app, such as copying files to a server or pushing to a CDN
        run: |
          echo "Deploying Angular app..."
